services:
  - type: web
    name: kodeshop
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan migrate --force
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: 
      
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: caboose.proxy.rlwy.net
      - key: DB_PORT
        value: 50715
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: pEFAffEbVJNpLBtAMgThASgkuMiNppDF
